### ISSUE TITLE
Configurar o GitHub Actions (Build e Deployment Automático)

### ISSUE THREAD

**Issue by geilsonrm** [gr-knowledge/github#11]
- Acesse o repositório no GitHub e vá em Settings > Actions > Runners.
- Clique em “New self-hosted runner” e siga as instruções para adicionar um runner no seu dispositivo.
- No Raspberry Pi, execute os comandos fornecidos para baixar e configurar o runner.
- (opcional) Para que o runner inicie automaticamente com o sistema, instale-o como um serviço
```
sudo ./svc.sh install
sudo ./svc.sh start
```

- No repositório, crie o diretório .github/workflows/ e adicione um arquivo YAML, por exemplo, deploy.yml.
- Defina o workflow para compilar o código e implantar na Raspberry Pi ".github/workflows/deploy.yml"
```
name: Build and Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # Ou outro branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest  # Faz o build no ambiente GitHub Actions
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Archive build
        run: tar -czf build.tar.gz dist/  # Compacta o diretório de build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build.tar.gz

  deploy:
    needs: build  # Aguarda o job "build" ser concluído
    runs-on: self-hosted  # Executa na Raspberry Pi
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Extract build
        run: tar -xzf build.tar.gz

      - name: Start application with PM2
        run: |
          pm2 stop minha-aplicacao || true
          pm2 start dist/index.js --name minha-aplicacao
          pm2 save
```

- Gere um par de chaves SSH no Raspberry Pi:
```
ssh-keygen -t rsa -b 4096 -C "github-actions@raspberrypi"
```

- Adicione a chave pública ao GitHub, permitindo que o runner tenha acesso ao repositório.
- Armazene a chave privada como um segredo no repositório GitHub para uso nos workflows.

## Instalar o Runner
```
tar xzf actions-runner-linux-arm64-<versão>.tar.gz
cd actions-runner
```
- Use o comando fornecido pelo GitHub para configurar o runner.
- Iniciar o Runner:
```
./run.sh
```
